server:
  port: 8888

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


minio:
  endpoint: http://ip:9000
  accessKey: ADMIN
  secretKey: AdminAdmin
  bucketName: bucketName
